# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lint"
  lane :lint do |options|
    swiftlint(
      mode: :lint,
      executable: "Pods/SwiftLint/swiftlint",
      output_file: options[:output_file],
      reporter: options[:reporter]
    )
  end

  desc "Take screenshot and Frame it"
  lane :take_screenshot do
    snapshot

    frameit(
      path: "fastlane/screenshots",
      white: true
    )
  end

  desc "Clean Build and Deploy to App Store"
  lane :release do

    # take_screenshot

    clear_derived_data

    gym

    deliver

    rocket
  end
end
