# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lint"
  lane :lint do |options|
    swiftlint(
      mode: :lint,
      executable: "Pods/SwiftLint/swiftlint",
      output_file: options[:output_file],
      reporter: options[:reporter]
    )
  end

  desc "Update version"
  lane :bump_version do |options|
    increment_version_number(bump_type: options[:bump_type])
    increment_build_number
  end

  desc "Take screenshot"
  lane :take_screenshot do
    snapshot

    # frameit(
    #   path: "fastlane/screenshots",
    #   white: true
    # )
  end

  desc "Clean Build and Deploy to App Store"
  lane :release do

    # take_screenshot

    clear_derived_data

    gym

    deliver

    rocket
  end
end
